name: base
channels:
  - conda-forge
  - defaults
  - numba

dependencies:
  - conda-forge::numpy=1.18.1
  - conda-forge::pandas=1.0.2
  - conda-forge::matplotlib=3.2.0
  - conda-forge::scikit-learn=0.23.0
