---
title: "wordshoal"
author: "Gustav Helms"
date: "11/8/2021"
output: html_document
---

```{r}
# loading packages
pacman::p_load(tidyverse, corpus, devtools, lubridate, flux, stopwords, seededlda, maps)

# Installing the latest version of quanteda and wordshoal
#devtools::install_github("https://github.com/quanteda/quanteda")
#remotes::install_github("kbenoit/wordshoal")
#devtools::install_github("quanteda/quanteda.corpora")

# Loading the packages
library(quanteda)
library(wordshoal)
library(quanteda.textmodels)
library(quanteda.corpora)
```


```{r}
# Importing data
df <- read_csv("./data/folketinget_2009_2021_raw.csv")
```

# --------------------------------------------------------------------------------------------------------------
# Preprocessing

```{r}
# Checking party labels
df %>% group_by(Parti) %>% count() %>% arrange(-n)
```


```{r}
# Filtering out parties 
parties_to_remove <- c("Uden for partierne", "Venstresocialisterne")


df <- df %>% 
  filter(!Parti %in% parties_to_remove) %>% 
  # Changing konservative folkeparti
  mutate(
  Parti = ifelse(Parti == "Konservative Folkeparti","Det Konservative Folkeparti", Parti),
  Parti = ifelse(Parti == "Det Radikale Venstre","Radikale Venstre", Parti),
  month_year_id = paste0(Year,"_", month(Date)) # Making a month and year unique variable
) %>% 
  #removing documents with less than 10 speaches
  group_by(id) %>% 
  filter(n() > 10) %>% ungroup() %>% 
  # Removing all formand because of procedural and lots of mistakes. 
  filter(!Title %in% c("Formanden","Formand")) %>% 
  # filtering out all duplicates
  group_by(doc_id) %>% filter(n() < 2) %>% ungroup()

# Adding column for whether party is in coalition

S <- c("Socialdemokratiet")
SR <- c("Socialdemokratiet", "Radikale Venstre","Socialistisk Folkeparti")
SRSF <- c("Socialdemokratiet", "Radikale Venstre","Socialistisk Folkeparti")
V <- c("Venstre")
VK <- c("Venstre", "Det Konservative Folkeparti")
VLAK <- c("Venstre", "Liberal Alliance", "Det Konservative Folkeparti")

df <- df %>% mutate(coalition = case_when(
  as.Date("2001-11-27") < Date & Date < as.Date("2011-11-03") ~ ifelse(Parti %in% VK, "Yes", "No"),
  as.Date("2011-11-03") < Date & Date < as.Date("2014-02-03") ~ ifelse(Parti %in% SRSF, "Yes", "No"),
  as.Date("2014-02-03") < Date & Date < as.Date("2015-06-28") ~ ifelse(Parti %in% SR, "Yes", "No"),
  as.Date("2015-06-28") < Date & Date < as.Date("2016-11-28") ~ ifelse(Parti %in% V, "Yes", "No"),
  as.Date("2016-11-28") < Date & Date < as.Date("2019-06-27") ~ ifelse(Parti %in% VLAK, "Yes", "No"),
  as.Date("2019-06-27") < Date ~ ifelse(Parti %in% S, "Yes", "No")))

```


# --------------------------------------------------------------------------------------------------------------
# Implementing the wordshoal function on our own data


```{r}
##############  TESTING NEW FUNCTION ############## 

get_theta <- function(data){
  corpus = quanteda::corpus(data)
  dfm <- dfm(tokens(corpus), remove_punct = TRUE, ignoredFeatures = stopwords("danish")) # matrix making
  wordshoalfit <- wordshoal::textmodel_wordshoal(dfm, groups = docvars(corpus, "id"), 
                                                 authors = docvars(corpus, "Name"))
  author_positions <- summary(wordshoalfit)$estimated.author.positions
  author_positions$row_names <- rownames(author_positions)

  fitdf <- merge(author_positions,
               docvars(corpus), 
               by.x = "row_names", by.y = "Name")
  fitdf <- subset(fitdf, !duplicated(row_names))
  theta_df <<- rbind(theta_df, fitdf)
}

testfunc <- function(data, year_list, party_list){
  
  # subsetting data frame based on arguments
  if(missing(data)){
    cat("Missing data-argument")
  } else if(hasArg(year_list) & hasArg(party_list)){
    data = data %>% filter(Year %in% year_list & Parti %in% party_list)
  } else if(hasArg(party_list)){
    data = data %>% filter(Parti %in% party_list)
  } else if(hasArg(year_list)){
    data = data %>% filter(Year %in% year_list)
  }
  
  # creating empty df to append to
  theta_df <<- data.frame()
  
  # create nested list of dataframes to which the shoal-function is applied
  nested = data %>% split(.$month_year_id)
  lapply(names(nested), function(x) get_theta(nested[[x]]))
  filename = paste0("./data/wordshoal_results/wordshoal_estimates_", min(year_list), "_", max(year_list), ".csv")
  write_csv(theta_df, filename)
}

# getting theta estimates for each speaker per month for Venstre & Socialdemokratiet
hep <- testfunc(data = df, year_list = c("2019"), party_list = c("Socialdemokratiet", "Venstre"))

# writing csv file manually
filename = paste0("./data/wordshoal_results/wordshoal_estimates_hep.csv")
write_csv(theta_df, filename)

```







```{r}
############## corpus per month ###################
years = seq(2014,2014) # Years to loop through

df_subset <- df %>% filter(Year %in% years) 
months = unique(df_subset$month_year_id) # input list

i=1
wordshoaler <- function(month) {
  cat(paste0("[ ] Shoaling Month ", month, ". Month: ", i, " out of ", length(months), "\n"))
  shoal_df = df_subset %>% filter(month_year_id == paste0(month))
  corpuseret = quanteda::corpus(shoal_df)
  dfmmm <- dfm(tokens(corpuseret), remove_punct = TRUE, ignoredFeatures = stopwords("danish")) # matrix making
  wordshoalfit <- wordshoal::textmodel_wordshoal(dfmmm, groups = docvars(corpuseret, "id"), 
                                                 authors = docvars(corpuseret, "Name"))
  author_positions <- summary(wordshoalfit)$estimated.author.positions
  author_positions$row_names <- rownames(author_positions)

  fitdf <- merge(author_positions,
               docvars(corpuseret), 
               by.x = "row_names", by.y = "Name")
  fitdf <- subset(fitdf, !duplicated(row_names))
  thetascores <<- rbind(thetascores, fitdf)
  i <<- i + 1
}

thetascores <- data.frame()
map(months, wordshoaler)

# writing the estimates
filename = paste0("./data/wordshoal_results/wordshoal_estimates_", min(years), "_", max(years), ".csv")
write_csv(thetascores, filename)
```

```{r}
# Aggregating to get the positions of the mean positon of the parties
author_positions <- summary(wordshoalfit)$estimated.author.positions
author_positions$row_names <- rownames(author_positions)

fitdf <- merge(author_positions,
               docvars(corpus), 
               by.x = "row_names", by.y = "Name")
fitdf <- subset(fitdf, !duplicated(row_names))


aggregate(theta ~ Parti, data = fitdf, mean)
```

# LDA 
```{r}
corpuseret = quanteda::corpus(df %>% filter(Year == 2011)) 
dfmmm <- dfm(tokens(corpuseret), remove_punct = TRUE, ignoredFeatures = stopwords("danish")) %>%
              dfm_trim(min_termfreq = 0.8, termfreq_type = "quantile",
                       max_docfreq = 0.1, docfreq_type = "prop") # matrix making


tmod_lda <- textmodel_lda(dfmmm, k = 10)


```

```{r}
terms(tmod_lda, 20)
```

```{r}
# Making the df into a corpus
corpus <- corpus(dfny)

# Create a data frame matrix (dfm)
dfm <- dfm(tokens(corpus), remove_punct = TRUE)

# Fitting the model
wordshoalfit <- 
    textmodel_wordshoal(dfm, #dir = c(7,1), # I cannot figure out what the 'dir' argument does
                        groups = docvars(corpus, "id"), 
                        authors = docvars(corpus, "Name"))

# Inspecting the output
summary(wordshoalfit) 

```