---
title: "R Notebook"
output: html_notebook
---

```{r}
# loading packages
pacman::p_load(tidyverse,stringdist, overlapping, lubridate)
```

```{r}
# Importing data
df <- read_csv("data/folketinget_2009_2021_raw.csv") %>% filter(Year %in% c(2019, 2020))

# Color pallette
pal <- wesanderson::wes_palette("Darjeeling1", 14, type = "continuous")

# Setting up the theme
theme_set(theme_minimal())
```


```{r}
##### Inspecting the distribution of speeches for each party

# Inspecting the data
df %>% count(Parti) %>%
  ggplot()+
  aes(x = reorder(Parti, -n), y = n, fill = Parti, label = n)+
  geom_col(width=0.5, position='dodge') +
  geom_text(position=position_dodge(0.5), vjust=-.50) + 
  scale_fill_manual(values = pal)+
  labs(y="Count", x="Parti", title = "Number of speeches from each party") +
  ylim(0, 13000)+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        legend.position = "none")
```
```{r}
#### Accumulated number of characters for each party
df %>% mutate(string_length = str_length(text)) %>% group_by(Parti) %>% 
  summarize(sum = sum(string_length)) %>%  
  ggplot()+
  aes(x = reorder(Parti, -sum), y = sum, fill = Parti)+
  geom_col(width=0.5, position='dodge') +
  scale_fill_manual(values = pal)+
  labs(y="Accumulated characters in speeches", x="Parti", title = "Total length of speeches for each party") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        legend.position = "none")

```

```{r}
##################################### NUMBER OF SPEECHES PR. MEMBER PR. YEAR ##########################################
# Wrangling  
df %>% group_by(Year, Name, Parti) %>% count() %>% 
  ungroup() %>% group_by(Year) %>% 
  summarise(mean = mean(n),
            median = median(n),
            fifth = quantile(n, probs = 0.05),
            nintyfifth = quantile(n, probs = 0.95)
            ) %>% pivot_longer(!Year) %>% 
  
  # Plotting
  ggplot()+
  aes(x = Year, y = value, color = name, linetype = name)+
  geom_line()+
  guides(linetype = FALSE)+
  scale_color_manual(labels = c("5th %ile", "Mean", "Median", "95th %ile"),
                     values = wesanderson::wes_palette("Darjeeling1"))+
  labs(x = "Year", 
       y = "Number of Speeches", 
       title = "Number of Speeches pr. year pr. person")+
  theme(legend.title = element_blank(), legend.key = element_rect(color = alpha("black", 0.2)))
  
  


```
```{r}
############################# LENGTH OF SPEECHES #######################################
# Wrangling  
df %>% mutate(text_length = str_length(text)) %>% 
  group_by(Year) %>% 
  summarise(mean = mean(text_length),
            median = median(text_length),
            fifth = quantile(text_length, probs = 0.05),
            nintyfifth = quantile(text_length, probs = 0.95)
            ) %>% pivot_longer(!Year) %>% 
  
  # Plotting
  ggplot()+
  aes(x = Year, y = value, color = name, linetype = name)+
  geom_line()+
  guides(linetype = FALSE)+
  scale_color_manual(labels = c("5th %ile", "Mean", "Median", "95th %ile"),
                     values = wesanderson::wes_palette("Darjeeling1"))+
  labs(x = "Year", 
       y = "Speech length", 
       title = "Speech legnth pr. year")+
  theme(legend.title = element_blank(), legend.key = element_rect(color = alpha("black", 0.2)))
  
```



```{r}
####################################### CHECKING WHETHER THERE ARE ANY SIMILAR NAMES #############################
# list of all names in the dataset
names = unique(df$Name)

# Creating a matrix with scores of how similar the names are
hep <- as.data.frame(stringdistmatrix(names, names, method = "jw"))

# Adding colnames to the matrix
colnames(hep) <- names

# Pivoting and filtering out similar records
hep %>% 
  mutate(
    name = names
    ) %>% 
  pivot_longer(!name, names_to = "name2", values_to = "similarity_scores") %>% 
  filter(similarity_scores <= 0.2 & similarity_scores !=0)

```




```{r}
################################### REMOVE SHORT SENTENCES #######################################

# Getting the length of all the strings
hep <- df %>% mutate(
  n_words = sapply(strsplit(text, " "), length)
)

# Threshold for how many words a speech should contatin 
limit = 50

# Summarizing the data
hep %>% 
  count(n_words) %>% 
  mutate(threshold = ifelse(n_words >= limit, paste("Below", limit, "words"), paste("Above", limit, "words"))) %>% 
  group_by(threshold) %>% 
  summarise("n_speeches" = sum(n)) %>% 
  mutate(percentage = n_speeches/sum(n_speeches))
  

```

```{r}
# Inspecting the data
hep %>% 
  filter(n_words > 50) %>%
  count(Parti) %>%
  ggplot()+
  aes(x = reorder(Parti, -n), y = n, fill = Parti, label = n)+
  geom_col(width=0.5, position='dodge') +
  geom_text(position=position_dodge(0.5), vjust=-.50) + 
  scale_fill_manual(values = pal)+
  labs(y="Count", x="Parti", title = "Number of speeches from each party") +
  ylim(0, 13000)+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        legend.position = "none")
  
```

```{r}
head(results)
```

# Inspecting the results
```{r}
#################### INSPECTING THE RESULTS ###########################
# Import the results
ML_results <- read_csv("./data/cv_results_subset.csv")
```

```{r}
# Plotting the results

ML_results %>% 
  group_by(Year) %>% 
  summarise(kappa = mean(kappa_test)) %>% 
  ggplot()+
  aes(x = Year, y = kappa)+
  geom_point()+
  geom_line(color = wesanderson::wes_palette("Darjeeling1")[2])+
  geom_smooth(method = "lm", alpha = 0.1, color = wesanderson::wes_palette("Darjeeling1")[1], size = 0.5)+
  ylim(0, 1)+
  labs(y = "Cohen Kappa score", title = "ML - Level of polarization in Folketinget")
```

# ------------------------ Plotting results of overlap ----------------------------------------
```{r}
# Load results dataframe
results <- read_csv("./data/agg_results_2009_2014.csv") %>% 
  # Creating date variable
  mutate(
  Date = str_replace(month_year_id, "_", "-"),
  Date = as.Date(paste0(Date, "-01"))
)

```

```{r}
results %>%  group_by(Parti, Date) %>% summarise(mean = mean(difference_score)) %>% ungroup() %>% group_by(Date) %>% summarise(mean = mean(mean)) %>% ungroup() %>% 
  ggplot()+
  aes(x = Date, y = mean)+
  geom_point()+
  geom_line(color = wesanderson::wes_palette("Darjeeling1")[2])+
  geom_smooth(method = "lm", alpha = 0.1, color = wesanderson::wes_palette("Darjeeling1")[1], size = 0.5)+
  ylim(0, 1)+
  labs(x = "Time",y = "Mean difference score", title = "Wordshoal - Level of polarization in Folketinget")
  
```

```{r}
results %>%  group_by(Parti, Date) %>% summarise(mean = mean(difference_score)) %>% ungroup() %>% 
  ggplot()+
  aes(x = Date, y = mean)+
  geom_point()+
  geom_line(aes(color = Parti))+
  geom_smooth(method = "lm", alpha = 0.1, color = wesanderson::wes_palette("Darjeeling1")[1], size = 0.5)+
  ylim(0, 1)+
  scale_color_manual(values = wesanderson::wes_palette("Darjeeling1", 10, type = "continuous")[2:10])+
  facet_wrap(~Parti)+
  labs(x = "Time",y = "Mean difference score", title = "Wordshoal - Level of polarization in Folketinget per party")+
  theme(legend.position = "none")
  
```


# ------------------------ Creating overlap variable ----------------------------------------


```{r}
# Loading the results
csv_files = list.files(pattern="*.csv", path = "data/wordshoal_results/", full.names = T) 
df = map_df(csv_files, read_csv)
df$time <- as.Date(paste(year(df$Date), month(df$Date), "01", sep = "-"))


df <- df %>% mutate(
  Parti = ifelse(Parti == "Det Radikale Venstre","Radikale Venstre", Parti)
)
```

```{r}
subset <- df %>% filter(month_year_id == "2011_5") %>% group_by(Parti) %>% filter(n() > 1) %>% ungroup()
parties <- unique(subset$Parti)
wide <- subset %>% pivot_wider(names_from = Parti, values_from = theta) 

list <- list()
# Adding the parties to the list
for(party in parties){
    list <- append(list, na.omit(select(wide, party)))
}

overlaps <- overlap(list)

```



```{r}
# FUNCTION
overlapper <- function(period){
  # Printing status
  print(paste0("[ ] Calculating overlaps for month: ", period, ". Number: ", i, " out of ", as.character(length(unique(df$month_year_id)))))
  
  # Subsetting the period and filtering out parties that only has 1 speech in a month
  subset <- df %>% filter(month_year_id == period) %>% group_by(Parti) %>% filter(n() > 1) %>% ungroup()
  
  # Making a list of parties
  parties <- unique(subset$Parti)
  
  # Converting into wide format
  wide <- subset %>% pivot_wider(names_from = Parti, values_from = theta) 
  
  # Creating an empty list
  list <- list()
  # Adding the parties to the list
  for(party in parties){
    list <- append(list,na.omit(select(wide, party)))
  }
  
  # Calculating the overlaps
  overlaps <- overlap(list)
  
  # Wringling the data
  results <- data.frame(overlaps$OV) %>% rownames_to_column("Parties") %>% 
    separate(Parties, c("From","To"), "-")
  
  # Making an empty data frame to append to
  end_results = data_frame()
  
  # Wrangling the result data frame
  for(party in parties){
    hep <- results %>% filter(From == party | To == party) %>% mutate(
      copy_from = From,
      From = ifelse(From == party, From, To),
      To = ifelse(To == party, copy_from, To)
    ) %>% select(-copy_from)
    
    end_results <- rbind(end_results, hep)
}

  # Adding month_year_id variable
  end_results$month_year_id <- period
  
  i <<- i + 1
  return(end_results)
}

```

```{r}
# Looping over the function
i = 1
heppe <- map_df(unique(df$month_year_id), overlapper)
```


```{r}
# Adding the aggregated columns to the results and exporting the data
agg <- df %>% group_by(month_year_id, Parti) %>% summarise(mean_theta = mean(theta), 
                                                           sd_theta = sd(theta))


jep <- left_join(heppe, tjep, by = c("From" = "Parti", Date = Date)) %>% 
  rename(
    Parti = From,
    overlap_with = To,
    overlap_score = overlaps.OV
  ) %>% mutate(
    difference_score = 1-overlap_score
  )
  select(month_year_id, Parti, overlap_with, overlap_score, mean_theta, sd_theta)

write_csv(results, "./data/agg_results_2009_2014.csv")
```


# ----------------------------------- MODELLING ---------------------------------------

```{r}
# Load results dataframe
results <- read_csv("./data/agg_results_2009_2014.csv") %>% 
  # Creating date variable
  mutate(
  Date = str_replace(month_year_id, "_", "-"),
  Date = as.Date(paste0(Date, "-01"))
)

######## Preprocessing #########3
# Agregating results into a single data frame - VERY MESSY i know
agg <- results %>% group_by(Parti, Date) %>% arrange(-overlap_score, .by_group = TRUE) %>% slice(1:3) %>%
  summarise(overlap_score = mean(overlap_score),
            difference_score = mean(difference_score)) 

agg <- left_join(x = agg, y = results %>% select(c(Parti, Date, mean_theta, sd_theta)), by = c("Parti" = "Parti", "Date" = "Date")) %>% group_by(Parti, Date) %>% slice(1) %>% ungroup()

# Adding a lag column for the predictors - difference_score and sd_theta
agg <- agg %>% mutate(
  lag_difference_score = lag(difference_score ),
  lag_sd_theta = lag(sd_theta)
)
```

```{r}
# Modelling with lmer!!!
pacman::p_load(lme4)

#  m1: InclusionSD_t2 ~ 1 + InclusionSD_t1 + Overlapping_t1 + (1 + InclusionSD_t1 + Overlapping_t1 | Party)
m1 <- lm(sd_theta ~ 1 + lag_sd_theta + lag_difference_score, data = agg)
summary(m1)

m2 <- lmer(sd_theta ~ 1 + lag_sd_theta + lag_difference_score + (1 + lag_sd_theta + lag_difference_score | Parti), data = agg)

summary(m2)
```


```{r}
# m3: Overlapping_t2 ~ 1 + InclusionSD_t1 + Overlapping_t1 + (1 + InclusionSD_t1 + Overlapping_t1 | Party)
m3 <- lm(difference_score ~ 1 + lag_difference_score + lag_sd_theta, data = agg)
summary(m3)

m4 <- lmer(difference_score ~ 1 + lag_difference_score + lag_sd_theta + (1 + lag_difference_score + lag_sd_theta | Parti), data = agg)
summary(m4)
```


