---
title: "wordshoal"
author: "Gustav Helms"
date: "11/8/2021"
output: html_document
---

```{r}
# loading packages
pacman::p_load(tidyverse, corpus, devtools, lubridate, flux, stopwords, seededlda, maps)

# Installing the latest version of quanteda and wordshoal
#devtools::install_github("https://github.com/quanteda/quanteda")
#remotes::install_github("kbenoit/wordshoal")
#devtools::install_github("quanteda/quanteda.corpora")

# Loading the packages
library(quanteda)
library(wordshoal)
library(quanteda.textmodels)
library(quanteda.corpora)
```


```{r}
# Importing data
df <- read_csv("./data/test_data3.csv")
```



# --------------------------------------------------------------------------------------------------------------
# Inspecting the data frame

```{r}
# Checking party labels
df %>% group_by(Parti) %>% count() %>% arrange(n) # sanity check

summary(df$Date)
```

# --------------------------------------------------------------------------------------------------------------
# Implementing the wordshoal function on our own data

```{r}
##############  TESTING NEW FUNCTION ############## 

get_theta <- function(data){
  corpus = quanteda::corpus(data)
  dfm <- dfm(tokens(corpus), remove_punct = TRUE, ignoredFeatures = stopwords("danish")) # matrix making
  wordshoalfit <- wordshoal::textmodel_wordshoal(dfm, groups = docvars(corpus, "id"), 
                                                 authors = docvars(corpus, "Name"))
  author_positions <- summary(wordshoalfit)$estimated.author.positions
  author_positions$row_names <- rownames(author_positions)

  fitdf <- merge(author_positions,
               docvars(corpus), 
               by.x = "row_names", by.y = "Name")
  fitdf <- subset(fitdf, !duplicated(row_names))
  theta_df <<- rbind(theta_df, fitdf)
}

testfunc <- function(data, year_list, party_list){
  
  # subsetting df based on arguments
  if(missing(data)){
    cat("No data argument")
  } else if(hasArg(year_list) & hasArg(party_list)){
    data = data %>% filter(Year %in% year_list & Parti %in% party_list)
  } else if(hasArg(party_list)){
    data = data %>% filter(Parti %in% party_list)
  } else if(hasArg(year_list)){
    data = data %>% filter(Year %in% year_list)
  }
  
  # creating empty df to append to
  theta_df <<- data.frame()
  
  # create nested list of dataframes to which the shoal-function is applied
  nested = data %>% split(.$month_year_id)
  lapply(names(nested), function(x) get_theta(nested[[x]]))
  filename = paste0("./data/wordshoal_results/wordshoal_estimates_", min(year_list), "_", max(year_list), ".csv")
  write_csv(theta_df, filename)
}

# getting theta estimates for each speaker per month for Venstre & Socialdemokratiet
hep <- testfunc(data = df, year_list = c("2019"), party_list = c("Socialdemokratiet", "Venstre"))

```

# --------------------------------- OLD METHOD -------------------------------------
```{r}
############## corpus per month ###################
years = seq(2009,2021) # Years to loop through

df_subset <- df %>% filter(Year %in% years) 
months = unique(df_subset$month_year_id) # input list

i=1
wordshoaler <- function(month) {
  cat(paste0("[ ] Shoaling Month ", month, ". Month: ", i, " out of ", length(months), "\n"))
  shoal_df = df_subset %>% filter(month_year_id == paste0(month))
  corpuseret = quanteda::corpus(shoal_df)
  dfmmm <- dfm(tokens(corpuseret), remove_punct = TRUE, ignoredFeatures = stopwords("danish")) # matrix making
  wordshoalfit <- wordshoal::textmodel_wordshoal(dfmmm, groups = docvars(corpuseret, "id"), 
                                                 authors = docvars(corpuseret, "Name"))
  author_positions <- summary(wordshoalfit)$estimated.author.positions
  author_positions$row_names <- rownames(author_positions)

  fitdf <- merge(author_positions,
               docvars(corpuseret), 
               by.x = "row_names", by.y = "Name")
  fitdf <- subset(fitdf, !duplicated(row_names))
  thetascores <<- rbind(thetascores, fitdf)
  i <<- i + 1
}

thetascores <- data.frame()
purrr::map(months, wordshoaler)

# writing the estimates
filename = paste0("./data/wordshoal_results/wordshoal_estimates_", min(years), "_", max(years), ".csv")
write_csv(thetascores, filename)
```

```{r}
# Aggregating to get the positions of the mean positon of the parties
author_positions <- summary(wordshoalfit)$estimated.author.positions
author_positions$row_names <- rownames(author_positions)

fitdf <- merge(author_positions,
               docvars(corpus), 
               by.x = "row_names", by.y = "Name")
fitdf <- subset(fitdf, !duplicated(row_names))


aggregate(theta ~ Parti, data = fitdf, mean)
```

# LDA 
```{r}
corpuseret = quanteda::corpus(df %>% filter(Year == 2011)) 
dfmmm <- dfm(tokens(corpuseret), remove_punct = TRUE, ignoredFeatures = stopwords("danish")) %>%
              dfm_trim(min_termfreq = 0.8, termfreq_type = "quantile",
                       max_docfreq = 0.1, docfreq_type = "prop") # matrix making


tmod_lda <- textmodel_lda(dfmmm, k = 10)

terms(tmod_lda, 20)

```
